### ISSUE TITLE
Revisions for BACKEND ROUTES

### ISSUE THREAD

**Issue by samsongs1991** [ecbell/OffBeatenPath#4]
I see that you have a backend route for "GET api/reviews/trails/:id/reviews" and I think to be consistent with the pattern of your other routes you should revise the url to "api/trails/:id/reviews". What would happen in the Trails Controller for that request would be something like ...
```js
def action
   trail = Trail.find(params[:id])
  render json: trail.reviews
end
```

...or something like that. 
Basically just use your associations to get the reviews for that trail.

**Comment by ecbell** [comment]
Ah yes, I see. I have a question on which route would be better:

**Comment by ecbell** [comment]
Ah yes! I see, thanks for finding that typo. I also have a quick question: could I just do the following instead of the nested route?

* `GET /api/trail/:id` - this will return a trail, and as you mentioned above, calling 'trail.reviews' would get me the index of all reviews for that specific trail (as trail_id and review_id are associated with each other in my tables). In that case `GET /api/trails/:id/reviews` would not be needed?

**Comment by samsongs1991** [comment]
That's right! However it kind of depends on what you want. If you make the request with just "/api/trails/:id" then anytime you make that GET request, you will always get back the reviews in addition to the trail details. Where as splitting it up will allow you to get the reviews separately. But in this case, I think it's easier and makes sense to get both the trail details and all of it's reviews from that one request to your backend.
